18 as a user i want to be able to view my course status so that i can know if i pass or fail
marktmng/sis_backend pull request #19
Opened 2024-07-30 10:41 UTC by hale2ian

2024-07-30 10:48 UTC, Gilgamesh3379 commented on .gitignore
> +db.sqlite3_bkp_20243007
what changes that you made in here?

2024-07-30 11:00 UTC, hale2ian commented on .gitignore
> +db.sqlite3_bkp_20243007
I added a .gitignore file to exclude adding directories venv1, .venv1 and files, db.sqlite3_bkp_20243007, verceldb_bkp_20243007 in the main branch.
because these are my local files that are not needed in the main branch.

2024-07-30 11:00 UTC, marktmng requested changes

2024-07-30 11:00 UTC, marktmng commented on backend/settings.py
Could you please work on postgresql  database please. I will provide you postman collection and variable.

2024-07-30 11:02 UTC, Gilgamesh3379 commented on .gitignore
> +db.sqlite3_bkp_20243007
That sounds good! Keeping unnecessary local files out of the main branch is a great practice. Thanks for letting me know.

2024-07-30 11:47 UTC, hale2ian commented on backend/settings.py
Ok. configuring it back to vercel DB.

2024-07-30 11:50 UTC, marktmng approved these changes

2024-07-30 11:54 UTC, Gilgamesh3379 approved these changes
ok. looks good! approved!

2024-07-30 11:56 UTC, merged

2024-08-05 09:30 UTC, hale2ian commented
- [ ] Selenium/Postman testing passed
- [ ] check commits
- [ ] check code changes
- [ ] provide feedbacks/reviews
- [ ] provide summary of changes made by developer
- [ ] Approve code change